apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.fullname" . }}-ad
  labels:
    app: ad
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: ad
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
