apiVersion: v1
kind: Service
metadata:
  name: ad
  labels:
    app: ad
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: ad
  ports:
    - protocol: TCP
      port: {{ .Values.global.ad_port}}
      targetPort: {{ .Values.global.ad_port }}
