apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.fullname" . }}-cart
  labels:
    app: cart
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
    - name: http
      port: 80
      targetPort: 8080
