apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app: checkout
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: checkout
  ports:
    - name: http
      port: 80
      targetPort: 8080
