apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.fullname" . }}-currency
  labels:
    app: currency
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: currency
  ports:
    - name: http
      port: 80
      targetPort: 8080
