apiVersion: v1
kind: Service
metadata:
  name: email
  labels:
    app: email
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: email
  ports:
    - name: http
      port: 8080
      targetPort: 8080
