apiVersion: v1
kind: Service
metadata:
  name: flagd-ui
  labels:
    app: flagd-ui
spec:
  type: ClusterIP
  selector:
    app: flagd-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
