apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.fullname" . }}-fraud-detection
  labels:
    app: fraud-detection
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: fraud-detection
  ports:
    - name: http
      port: 8080
      targetPort: 8080
