apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy
  labels:
    app: frontend-proxy
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend-proxy
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP