apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
