apiVersion: v1
kind: Service
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  selector:
    app: load-generator
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
