apiVersion: v1
kind: Service
metadata:
  name: load-generator
  labels:
    app: load-generator
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: load-generator
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
