apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
