apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  labels:
    app: product-catalog
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: product-catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
