apiVersion: v1
kind: Service
metadata:
  name: quote
  labels:
    app: quote
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: quote
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
