apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  selector:
    app: recommendation
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
